### PR TITLE
refactor(dist): update bundled files

### PR DESCRIPTION
**Pull request by tylerbrandt**
## Summary

**BREAKING**: Drop support for `window.optimizelyClient`, as presaged in the [CHANGELOG](https://github.com/optimizely/javascript-sdk/blob/master/packages/optimizely-sdk/CHANGELOG.MD#213---august-21-2018).

- Pull in changes from 2.3.x, to ensure that both optimizely.browser.umd.js and optimizely.browser.umd.min.js are defined.
- Refactor those changes to use webpack config/index.browser code instead of appending to the bundle after-the-fact.
- Actually install `webpack` as a devDependency rather than always using latest

In addition to fixing the issue from #187 in this branch, it simplifies the build script.

## Test plan

Existing unit tests pass since the "node" API for index.browser.js wasn't changed.

Created a test file called "dist/test.html" and loaded it in a browser (as well as an equivalent one that loads the min.js variant):
```html
<!DOCTYPE html>
<html>

<head>
	<script src="/optimizely.browser.umd.js"></script>
</head>

<body>
	<h1>Hello</h1>
	<script>
		console.log('optimizelySdk', typeof optimizelySdk);
		console.log('optimizelyClient', typeof optimizelyClient);
	</script>
</body>

</html>
```
Ensured that it logged "object" for the first, and "undefined" for the second:
screen shot 2018-11-14 at 3 50 30 pm

## Issues
- OASIS-3790

### CODE REVIEW

**Comment by mikeng13** [comment]
This needs to be accompanied by a change to our public docs when we release. Can you include the an entry for a breaking change under unreleased for the deprecated `optimizelyClient` reference?

**Comment by tylerbrandt** [comment]
> This needs to be accompanied by a change to our public docs when we release. Can you include the an entry for a breaking change under unreleased for the deprecated optimizelyClient reference?

Why? The docs already only refer to `window.optimizelySdk` and we published a changelog entry in August that said that `window.optimizelyClient` is going away.

**Comment by tylerbrandt** [comment]
Any comment on this?

> perhaps they should be modified to expect window.optimizelySdk; comment if you agree/disagree

**Comment by mikeng13** [comment]
> Any comment on this?
> 
> > perhaps they should be modified to expect window.optimizelySdk; comment if you agree/disagree

I agree we should be doing this check in our tests.

**Comment by mikeng13** [comment]
> Hmm I can't figure out how to set it up with webpack/karma. Might have to be an integration-type test. Added #190

Alright we'll take care of it in another PR then.

**Pull request merged**
