### PR TITLE
npm already adds node_modules/.bin to PATH

### PR DESCRIPTION
**Pull request by jasonkarns**
Again, same issue as https://github.com/optimizely/javascript-sdk/pull/56, there is no need to point directly at the node_modules bin because npm purposefully prepends `$(npm bin)` to `PATH` when running scripts.

(Which is in addition to the fact that `./node_modules/karma/bin/karma` is the wrong path in the first place. It's brittle and reliant on karma always keeping that file in the same location and with the same name. Correct location for binaries is where npm symlinks them, as instructed by the `bin` property of package.json: `./node_modules/.bin/karma`. But again, all this is unnecessary because npm has the feature specifically to avoid this.)

### CODE REVIEW

**Comment by caitlinrubin-optimizely** [comment]
Hi @jasonkarns we're reviewing that change and we're going to look into the travis test failures as well. Thanks!

**Comment by caitlinrubin-optimizely** [comment]
@jasonkarns can you please pull our latest changes to master and re-push your fix?

**Comment by jasonkarns** [comment]
done. still failing for unrelated reasons

**Comment by mikeng13** [comment]
Closing this as it is no longer relevant.

**Pull request closed without merging**
