### PR TITLE
chore(GitHub): Add CODEOWNERS

### PR DESCRIPTION
**Pull request by spencerwilson-optimizely**
Could also be `* @optimizely/fullstack-devs`, but I'm not sure we want to email everyone on the team for every SDK repo.

### CODE REVIEW

**Comment by tylerbrandt** [comment]
I would prefer to use teams for this. Could we (should we) create an `@optimizely/javascript-sdk` team?

**Comment by tylerbrandt** [comment]
PS I have been using fullstack-devs in fullstack-sdk-compatibility-suite and nobody has complained...

**Comment by spencerwilson-optimizely** [comment]
> Could we (should we) create an @optimizely/javascript-sdk team?

I think that's reasonable, though not sure if having the team defined within an organization precludes people from outside the org being on the team. If the team is semantically 'required reviewers' though, well, that probably just means optinauts, anyway.

> I have been using fullstack-devs in fullstack-sdk-compatibility-suite and nobody has complained...

heh, true, but all SDK folks have _some_ stake in that repo, whereas (arguably) Sally iOS Expert is probably less interested in the PR-by-PR goings-on of javascript-sdk.

**Comment by mikeng13** [comment]
build-e2e

**Comment by mikeng13** [comment]
Closing as obsolete

**Pull request closed without merging**
