### PR TITLE
Input validation in Activate, Track and GetVariation methods.

### PR DESCRIPTION
**Pull request by mfahadahmed**

### CODE REVIEW

**Comment by mfahadahmed** [comment]
@mikeng13, we currently have two different validators (user_id_validator and string_value_validator) which are doing the same task of validating string inputs.
Should I remove the user_id_validator and validate User ID with string_value_validator? Then we can easily change the first parameter of __validateInputs to string values map.

**Comment by mikeng13** [comment]
@mfahadahmed you can repurpose the `__validateInputs` method (refactor) to take in the `values` arg and perform all the needed validation inside of that method, including null checks.

**Comment by mfahadahmed** [comment]
@mikeng13, The required changes have been done. Please verify.

**Comment by mikeng13** [comment]
build

**Pull request merged**
