### PR TITLE
[FSSDK-9621] add persistentCacheProvider option for instantiation

### PR DESCRIPTION
**Pull request by raju-opti**
## Summary
- make the react native persistent cache implementation configurable 

## Test plan
- added relevant tests

## Issues
- FSSDK-9621

### CODE REVIEW

**Comment by mikechu-optimizely** [comment]
@anton-patrushev Was this what you had in mind for [your posted issue](https://github.com/optimizely/react-sdk/issues/166)?

**Review by mikechu-optimizely — APPROVED** [review]
LGTM.  

I think it's worthwhile to spin up an Expo project and include this branch's dist for manual testing and pass in our own store.

**Comment by muzahidul-opti** [comment]
Do we need to support both? If `mmkv` meets our requirements, perhaps we can gradually discontinue `async-storage`.

**Comment by raju-opti** [comment]
> Do we need to support both? If `mmkv` meets our requirements, perhaps we can gradually discontinue `async-storage`.

@muzahidul-opti this PR allows the user to provide their own peristentCache, so that they can use anything they like. By default we are still using async-storage.

**Comment by mikechu-optimizely** [comment]
> Do we need to support both? If `mmkv` meets our requirements, perhaps we can gradually discontinue `async-storage`.

Good qustion @muzahidul-opti .  Thanks for asking it.

**Pull request merged**
